version: '3'
services:
  django:
    build:
      context: ./cnuchatbot
      dockerfile: Dockerfile
    command: uwsgi --http :8001 uwsgi.ini
    volumes:
      - ./cnuchatbot:/srv/cnuchatbot
      - ./log:/var/log/uwsgi
    ports:
      - "8001:8000"
