# Generated by Django 3.1.7 on 2022-02-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalStartTime', models.IntegerField(null=True, verbose_name='오픈시간')),
                ('normalEndTime', models.IntegerField(null=True, verbose_name='마감시간')),
                ('closedNotice', models.TextField(null=True, verbose_name='마감후공지')),
                ('normalNotice', models.TextField(null=True, verbose_name='공지')),
            ],
        ),
    ]
