# Generated by Django 3.1.7 on 2022-02-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0002_shuttle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuttle',
            name='departureTime',
            field=models.TimeField(null=True, verbose_name='출발시간'),
        ),
    ]
