# Generated by Django 3.1.7 on 2022-02-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0003_auto_20220227_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shuttle',
            name='departureTime',
        ),
        migrations.AddField(
            model_name='shuttle',
            name='aline_departureTime',
            field=models.TimeField(null=True, verbose_name='a노선 출발시간'),
        ),
        migrations.AddField(
            model_name='shuttle',
            name='bline_departureTime',
            field=models.TimeField(null=True, verbose_name='b노선 출발시간'),
        ),
    ]
