# Generated by Django 3.1.7 on 2022-02-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0004_auto_20220227_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShuttleA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departureTime', models.TimeField(null=True, verbose_name='a노선 출발시간')),
            ],
        ),
        migrations.CreateModel(
            name='ShuttleB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departureTime', models.TimeField(null=True, verbose_name='b노선 출발시간')),
            ],
        ),
        migrations.DeleteModel(
            name='Shuttle',
        ),
    ]
